# Generated by Django 2.1 on 2019-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.FileField(upload_to='signature'),
        ),
    ]
