# Generated by Django 2.1 on 2019-11-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20191119_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank='true', null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.CharField(max_length=1024),
        ),
    ]
