# Generated by Django 2.1 on 2019-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20191119_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.CharField(blank='true', max_length=1024),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank='true', max_length=2048),
        ),
    ]
